# Site settings
title: wnpers blog
email: wnpers@gmail.com
description: "life"
baseurl: "/blog"
url: "http://yourdomain.com"
twitter_username: wnpers
github_username:  wnpers

# Build settings
markdown: kramdown
permalink: pretty
paginate: 2
paginate_path: "page:num"
