# Site settings
title: wnpers blog
email: wnpers@gmail.com
description: ""
baseurl: "/blog"
url: "http://wnpers.github.io"
twitter_username: wnpers
github_username:  wnpers

# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
paginate: 6
paginate_path: "page:num"
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
highlighter: rouge